#!/bin/bash

set -u
set -e


ERRP='::::::>>'
ERRS='<<::::::'
FIXNAME=$(echo "$1" | _fixnamer)

if [[ "${1}" == "$FIXNAME" ]]; then
	echo "${ERRP}Skip${ERRS} $1"
elif [[ -f "$FIXNAME" ]]; then
	echo "${ERRP}Target Exists${ERRS} $1 => $FIXNAME"
else
	echo "$FIXNAME"
	\mv -n "$1" "$FIXNAME"
fi


